/* ─────────────────────────────────────────────
   Grocery Confidential — listdatabase.js
   Edit this file to manage your categories and items.
   Do not touch app.js.
   ───────────────────────────────────────────── */

// ══════════════════════════════════════════════
//  CATEGORIES
//  Fields: id (unique, no spaces), name, emoji
// ══════════════════════════════════════════════

const DEFAULT_CATEGORIES = [
  { id: 'vegetables',   name: 'Vegetables',          emoji: '🥦' },
  { id: 'protein',      name: 'Protein',              emoji: '🥩' },
  { id: 'carbs',        name: 'Carbs',                emoji: '🍞' },
  { id: 'dairy',        name: 'Dairy',                emoji: '🥛' },
  { id: 'fruits',       name: 'Fruits',               emoji: '🍎' },
  { id: 'nuts_seeds',   name: 'Nuts & Seeds',          emoji: '🥜' },
  { id: 'oils',         name: 'Oils',                 emoji: '🫒' },
  { id: 'condiments',   name: 'Condiments & Sauces',  emoji: '🫙' },
  { id: 'herbs',        name: 'Herbs & Powders',       emoji: '🌿' },
  { id: 'baking',       name: 'Baking',               emoji: '🧁' },
  { id: 'cold_cuts',    name: 'Cold Cuts',             emoji: '🥓' },
  { id: 'drinks',       name: 'Drinks',               emoji: '🥤' },
  { id: 'cat_goods',    name: 'Cat Goods',             emoji: '🐱' },
  { id: 'canned_goods', name: 'Canned Goods',          emoji: '🥫' },
  { id: 'household',    name: 'Household',             emoji: '🧹' },
  { id: 'supplements',  name: 'Supplements',           emoji: '💊' },
  { id: 'other',        name: 'Other',                emoji: '📦' },
];

// ══════════════════════════════════════════════
//  ITEMS
//  Fields:
//    id         — unique string, no spaces
//    name       — display name
//    categoryId — must match an id above
//    unit       — optional (e.g. 'kg', 'pack') or ''
// ══════════════════════════════════════════════

const DEFAULT_ITEMS = [
  // ── Vegetables ───────────────────────────────
  { id: 'veg01', name: 'Asparagus',       categoryId: 'vegetables', unit: '' },
  { id: 'veg02', name: 'Avocado',         categoryId: 'vegetables', unit: '' },
  { id: 'veg03', name: 'Bell Peppers',    categoryId: 'vegetables', unit: '' },
  { id: 'veg04', name: 'Bimi',            categoryId: 'vegetables', unit: '' },
  { id: 'veg05', name: 'Broccoli',        categoryId: 'vegetables', unit: '' },
  { id: 'veg06', name: 'Carrot',          categoryId: 'vegetables', unit: '' },
  { id: 'veg07', name: 'Cucumber',        categoryId: 'vegetables', unit: '' },
  { id: 'veg08', name: 'Garlic',          categoryId: 'vegetables', unit: '' },
  { id: 'veg09', name: 'Ginger',          categoryId: 'vegetables', unit: '' },
  { id: 'veg10', name: 'Leek',            categoryId: 'vegetables', unit: '' },
  { id: 'veg11', name: 'Lemon',           categoryId: 'vegetables', unit: '' },
  { id: 'veg12', name: 'Lime',            categoryId: 'vegetables', unit: '' },
  { id: 'veg13', name: 'Mais',            categoryId: 'vegetables', unit: '' },
  { id: 'veg14', name: 'Mushroom',        categoryId: 'vegetables', unit: '' },
  { id: 'veg15', name: 'Onion',           categoryId: 'vegetables', unit: '' },
  { id: 'veg16', name: 'Paprika',         categoryId: 'vegetables', unit: '' },
  { id: 'veg17', name: 'Potato',          categoryId: 'vegetables', unit: '' },
  { id: 'veg18', name: 'Rucola',          categoryId: 'vegetables', unit: '' },
  { id: 'veg19', name: 'Spring Onion',    categoryId: 'vegetables', unit: '' },
  { id: 'veg20', name: 'Sweet Potato',    categoryId: 'vegetables', unit: '' },
  { id: 'veg21', name: 'Tomato',          categoryId: 'vegetables', unit: '' },
  { id: 'veg22', name: 'Edamame',         categoryId: 'vegetables', unit: '' },
  { id: 'veg23', name: 'Shallot',         categoryId: 'vegetables', unit: '' },
  { id: 'veg24', name: 'Peas',            categoryId: 'vegetables', unit: '' },
  { id: 'veg25', name: 'Celery',          categoryId: 'vegetables', unit: '' },
  // ── Protein ──────────────────────────────────
  { id: 'pro00', name: 'Chicken',             categoryId: 'protein', unit: '' },
  { id: 'pro01', name: 'Chicken Thigh',       categoryId: 'protein', unit: '' },
  { id: 'pro02', name: 'Chicken Filet',       categoryId: 'protein', unit: '' },
  { id: 'pro03', name: 'Eggs',               categoryId: 'protein', unit: '' },
  { id: 'pro04', name: 'Minced Beef',         categoryId: 'protein', unit: '' },
  { id: 'pro05', name: 'Minced Half/Half',    categoryId: 'protein', unit: '' },
  { id: 'pro06', name: 'Salmon',             categoryId: 'protein', unit: '' },
  { id: 'pro07', name: 'Smoked Salmon',       categoryId: 'protein', unit: '' },
  { id: 'pro08', name: 'Steak',              categoryId: 'protein', unit: '' },
  { id: 'pro09', name: 'Duck',               categoryId: 'protein', unit: '' },
  { id: 'pro10', name: 'Shrimp',             categoryId: 'protein', unit: '' },
  { id: 'pro11', name: 'Surimi',             categoryId: 'protein', unit: '' },
  { id: 'pro12', name: 'Guanciale',          categoryId: 'protein', unit: '' },
  { id: 'pro13', name: 'Pancetta',           categoryId: 'protein', unit: '' },
  { id: 'pro14', name: 'Smoked Bacon Cubes', categoryId: 'protein', unit: '' },
  { id: 'pro15', name: 'Italian Sausage',    categoryId: 'protein', unit: '' },
  { id: 'pro16', name: 'Ground Lamb',        categoryId: 'protein', unit: '' },
  // ── Carbs ────────────────────────────────────
  { id: 'car01', name: 'Bread',               categoryId: 'carbs', unit: '' },
  { id: 'car02', name: 'Flammekeuche Dough',  categoryId: 'carbs', unit: '' },
  { id: 'car03', name: 'Fusilli',             categoryId: 'carbs', unit: '' },
  { id: 'car04', name: 'Gnocchi',             categoryId: 'carbs', unit: '' },
  { id: 'car05', name: 'Lasagna',             categoryId: 'carbs', unit: '' },
  { id: 'car06', name: 'Noodles',             categoryId: 'carbs', unit: '' },
  { id: 'car07', name: 'Oatmeal',             categoryId: 'carbs', unit: '' },
  { id: 'car08', name: 'Penne',               categoryId: 'carbs', unit: '' },
  { id: 'car09', name: 'Quinoa',              categoryId: 'carbs', unit: '' },
  { id: 'car10', name: 'Rice',                categoryId: 'carbs', unit: '' },
  { id: 'car11', name: 'Spaghetti',           categoryId: 'carbs', unit: '' },
  { id: 'car12', name: 'Tagliatelle',         categoryId: 'carbs', unit: '' },
  { id: 'car13', name: 'Tortellini',          categoryId: 'carbs', unit: '' },
  { id: 'car14', name: 'Wraps',               categoryId: 'carbs', unit: '' },
  // ── Dairy ────────────────────────────────────
  { id: 'dai01', name: 'Butter',          categoryId: 'dairy', unit: '' },
  { id: 'dai02', name: 'Cheese',          categoryId: 'dairy', unit: '' },
  { id: 'dai03', name: 'Coconut Milk',    categoryId: 'dairy', unit: '' },
  { id: 'dai04', name: 'Cooking Cream',   categoryId: 'dairy', unit: '' },
  { id: 'dai05', name: 'Crème Fraîche',   categoryId: 'dairy', unit: '' },
  { id: 'dai06', name: 'Goat Cheese',     categoryId: 'dairy', unit: '' },
  { id: 'dai07', name: 'Grated Cheese',   categoryId: 'dairy', unit: '' },
  { id: 'dai08', name: 'Heavy Cream',     categoryId: 'dairy', unit: '' },
  { id: 'dai09', name: 'Milk',            categoryId: 'dairy', unit: '' },
  { id: 'dai10', name: 'Morbier',         categoryId: 'dairy', unit: '' },
  { id: 'dai11', name: 'Mozzarella',      categoryId: 'dairy', unit: '' },
  { id: 'dai12', name: 'Munster',         categoryId: 'dairy', unit: '' },
  { id: 'dai13', name: 'Parmigiano',      categoryId: 'dairy', unit: '' },
  { id: 'dai14', name: 'Quark (Kwark)',   categoryId: 'dairy', unit: '' },
  { id: 'dai15', name: 'Sour Cream',      categoryId: 'dairy', unit: '' },
  { id: 'dai16', name: 'Yoghurt',         categoryId: 'dairy', unit: '' },
  { id: 'dai17', name: 'Cheddar',         categoryId: 'dairy', unit: '' },
  // ── Fruits ───────────────────────────────────
  { id: 'fru01', name: 'Apple',       categoryId: 'fruits', unit: '' },
  { id: 'fru02', name: 'Banana',      categoryId: 'fruits', unit: '' },
  { id: 'fru03', name: 'Blackberry',  categoryId: 'fruits', unit: '' },
  { id: 'fru04', name: 'Kiwi',        categoryId: 'fruits', unit: '' },
  { id: 'fru05', name: 'Mandarin',    categoryId: 'fruits', unit: '' },
  { id: 'fru06', name: 'Red Grapes',  categoryId: 'fruits', unit: '' },
  // ── Nuts & Seeds ─────────────────────────────
  { id: 'nut01', name: 'Pine',          categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut02', name: 'Almonds',       categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut03', name: 'Pecan',         categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut04', name: 'Cashew',        categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut05', name: 'Pistachio',     categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut06', name: 'Sesame Seeds',  categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut07', name: 'Fennel Seeds',  categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut08', name: 'Chia Seeds',    categoryId: 'nuts_seeds', unit: '' },
  // ── Oils ─────────────────────────────────────
  { id: 'oil01', name: 'White Vinegar',   categoryId: 'oils', unit: '' },
  { id: 'oil02', name: 'Rice Vinegar',    categoryId: 'oils', unit: '' },
  { id: 'oil03', name: 'Sesame Oil',      categoryId: 'oils', unit: '' },
  { id: 'oil04', name: 'Chili Oil',       categoryId: 'oils', unit: '' },
  { id: 'oil05', name: 'Sun Flower Oil',  categoryId: 'oils', unit: '' },
  { id: 'oil06', name: 'Balsamico Cream', categoryId: 'oils', unit: '' },
  { id: 'oil07', name: 'Olive Oil',       categoryId: 'oils', unit: '' },
  { id: 'oil08', name: 'Mirin',           categoryId: 'oils', unit: '' },
  // ── Condiments & Sauces ──────────────────────
  { id: 'con01', name: 'BBQ Sauce',              categoryId: 'condiments', unit: '' },
  { id: 'con02', name: 'Cider Vinegar',           categoryId: 'condiments', unit: '' },
  { id: 'con03', name: 'Gochujang',              categoryId: 'condiments', unit: '' },
  { id: 'con04', name: 'Hoisin Sauce',            categoryId: 'condiments', unit: '' },
  { id: 'con05', name: 'Honey',                  categoryId: 'condiments', unit: '' },
  { id: 'con06', name: 'Ketchup',                categoryId: 'condiments', unit: '' },
  { id: 'con07', name: 'LKK Black Bean Garlic',  categoryId: 'condiments', unit: '' },
  { id: 'con08', name: 'Mayonaise',              categoryId: 'condiments', unit: '' },
  { id: 'con09', name: 'Mustard',                categoryId: 'condiments', unit: '' },
  { id: 'con10', name: 'Nocciolata',             categoryId: 'condiments', unit: '' },
  { id: 'con11', name: 'Pesto',                  categoryId: 'condiments', unit: '' },
  { id: 'con12', name: 'Soy Sauce',              categoryId: 'condiments', unit: '' },
  { id: 'con13', name: 'Sriracha',               categoryId: 'condiments', unit: '' },
  { id: 'con14', name: 'Sriracha Mayo',           categoryId: 'condiments', unit: '' },
  { id: 'con15', name: 'Tomato Paste',            categoryId: 'condiments', unit: '' },
  { id: 'con16', name: 'Truffle Mayo',            categoryId: 'condiments', unit: '' },
  { id: 'con17', name: 'Water',                  categoryId: 'condiments', unit: '', pantry: true  },
  { id: 'con18', name: 'Worcestershire Sauce',   categoryId: 'condiments', unit: '' },
  // ── Herbs & Powders ──────────────────────────
  { id: 'her01', name: 'Basil',                          categoryId: 'herbs', unit: '' },
  { id: 'her02', name: 'Bay Leaves',                     categoryId: 'herbs', unit: '' },
  { id: 'her03', name: 'Black Pepper',                   categoryId: 'herbs', unit: '', pantry: true  },
  { id: 'her04', name: 'Burrito Kruidenmix Santa Maria', categoryId: 'herbs', unit: '' },
  { id: 'her05', name: 'Chili Con Carne',                categoryId: 'herbs', unit: '' },
  { id: 'her06', name: 'Garam Masala',                   categoryId: 'herbs', unit: '' },
  { id: 'her07', name: 'Garlic Powder',                  categoryId: 'herbs', unit: '' },
  { id: 'her08', name: 'MSG',                            categoryId: 'herbs', unit: '' },
  { id: 'her09', name: 'Onion Powder',                   categoryId: 'herbs', unit: '' },
  { id: 'her10', name: 'Parsley',                        categoryId: 'herbs', unit: '' },
  { id: 'her11', name: 'PB2',                            categoryId: 'herbs', unit: '' },
  { id: 'her12', name: 'Red Pepper Flakes',              categoryId: 'herbs', unit: '' },
  { id: 'her13', name: 'Rosemary',                       categoryId: 'herbs', unit: '' },
  { id: 'her14', name: 'Salt',                           categoryId: 'herbs', unit: '', pantry: true  },
  { id: 'her15', name: 'Thyme',                          categoryId: 'herbs', unit: '' },
  // ── Baking ───────────────────────────────────
  { id: 'bak01', name: 'Chocolate Chips',  categoryId: 'baking', unit: '' },
  { id: 'bak02', name: 'Cooking Chocolate',categoryId: 'baking', unit: '' },
  { id: 'bak03', name: 'Crystal Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak04', name: 'Bastard Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak05', name: 'Flour',            categoryId: 'baking', unit: '' },
  { id: 'bak06', name: 'Cinnamon',         categoryId: 'baking', unit: '' },
  { id: 'bak07', name: 'Baking Soda',      categoryId: 'baking', unit: '' },
  { id: 'bak08', name: 'Vanilla Extract',  categoryId: 'baking', unit: '' },
  { id: 'bak09', name: 'Brown Sugar',      categoryId: 'baking', unit: '' },
  { id: 'bak10', name: 'Sugar',            categoryId: 'baking', unit: '' },
  { id: 'bak11', name: 'Baking Powder',    categoryId: 'baking', unit: '' },
  { id: 'bak12', name: 'Vanilla Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak13', name: 'Almond Flour',     categoryId: 'baking', unit: '' },
  // ── Cold Cuts ────────────────────────────────
  { id: 'cut01', name: 'Achterham',    categoryId: 'cold_cuts', unit: '' },
  { id: 'cut02', name: 'Beenham',      categoryId: 'cold_cuts', unit: '' },
  { id: 'cut03', name: 'Cheese Cuts',  categoryId: 'cold_cuts', unit: '' },
  { id: 'cut04', name: 'Chorizo',      categoryId: 'cold_cuts', unit: '' },
  { id: 'cut05', name: 'Salami',       categoryId: 'cold_cuts', unit: '' },
  // ── Drinks ───────────────────────────────────
  { id: 'drk01', name: 'Cola',          categoryId: 'drinks', unit: '' },
  { id: 'drk02', name: 'Diplomatico',   categoryId: 'drinks', unit: '' },
  { id: 'drk03', name: 'Guinness',      categoryId: 'drinks', unit: '' },
  { id: 'drk04', name: "Jus d'orange",  categoryId: 'drinks', unit: '' },
  { id: 'drk05', name: 'Nescafé Gold',  categoryId: 'drinks', unit: '' },
  { id: 'drk06', name: 'White Wine',    categoryId: 'drinks', unit: '' },
  { id: 'drk07', name: 'Beer',          categoryId: 'drinks', unit: '' },
  // ── Cat Goods ────────────────────────────────
  { id: 'cat01', name: 'Kibble',          categoryId: 'cat_goods', unit: '' },
  { id: 'cat02', name: 'Gourmet Mousse',  categoryId: 'cat_goods', unit: '' },
  { id: 'cat03', name: 'Litter',          categoryId: 'cat_goods', unit: '' },
  { id: 'cat04', name: 'L-Lysine',        categoryId: 'cat_goods', unit: '' },
  { id: 'cat05', name: 'Catisfaction',    categoryId: 'cat_goods', unit: '' },
  // ── Canned Goods ─────────────────────────────
  { id: 'can01', name: 'Canned Tomatoes',                  categoryId: 'canned_goods', unit: '' },
  { id: 'can02', name: 'Canned Tuna',                      categoryId: 'canned_goods', unit: '' },
  { id: 'can03', name: 'Bonduelle Bonenmix',               categoryId: 'canned_goods', unit: '' },
  { id: 'can04', name: 'Bonduelle Mexicana Mix',           categoryId: 'canned_goods', unit: '' },
  { id: 'can05', name: 'Kühne Rauwkost',                   categoryId: 'canned_goods', unit: '' },
  { id: 'can06', name: 'Pickled Green Pepper',             categoryId: 'canned_goods', unit: '' },
  { id: 'can07', name: 'Knorr Wereldgerechten Burrito',    categoryId: 'canned_goods', unit: '' },
  { id: 'can08', name: 'Pickled Red Onion',                categoryId: 'canned_goods', unit: '' },
  // ── Household ────────────────────────────────
  { id: 'hsh01', name: 'Aloe Vera Lotion',           categoryId: 'household', unit: '' },
  { id: 'hsh02', name: 'Blue Wonder Disinfect Wipes', categoryId: 'household', unit: '' },
  { id: 'hsh03', name: 'Boterhamzakje',              categoryId: 'household', unit: '' },
  { id: 'hsh04', name: 'Condoms',                    categoryId: 'household', unit: '' },
  { id: 'hsh05', name: 'Cotton Buds',                categoryId: 'household', unit: '' },
  { id: 'hsh06', name: 'Cotton Pads Round',          categoryId: 'household', unit: '' },
  { id: 'hsh07', name: 'Dish Soap',                  categoryId: 'household', unit: '' },
  { id: 'hsh08', name: 'Dishwasher Rinse',           categoryId: 'household', unit: '' },
  { id: 'hsh09', name: 'Dishwasher Salt',            categoryId: 'household', unit: '' },
  { id: 'hsh10', name: 'Dishwasher Tablets',         categoryId: 'household', unit: '' },
  { id: 'hsh11', name: 'Green Soap',                 categoryId: 'household', unit: '' },
  { id: 'hsh12', name: 'Hand Soap',                  categoryId: 'household', unit: '' },
  { id: 'hsh13', name: 'Kitchen Paper',              categoryId: 'household', unit: '' },
  { id: 'hsh14', name: 'Laundry Soap',               categoryId: 'household', unit: '' },
  { id: 'hsh15', name: 'Nose Spray',                 categoryId: 'household', unit: '' },
  { id: 'hsh16', name: 'Paracetamol',                categoryId: 'household', unit: '' },
  { id: 'hsh17', name: 'Skewers',                    categoryId: 'household', unit: '' },
  { id: 'hsh18', name: 'Throat Medicine',            categoryId: 'household', unit: '' },
  { id: 'hsh19', name: 'Tissues',                    categoryId: 'household', unit: '' },
  { id: 'hsh20', name: 'Toilet Paper',               categoryId: 'household', unit: '' },
  { id: 'hsh21', name: 'Toothbrush',                 categoryId: 'household', unit: '' },
  { id: 'hsh22', name: 'Toothpaste',                 categoryId: 'household', unit: '' },
  { id: 'hsh23', name: 'Toothpick Floss',            categoryId: 'household', unit: '' },
  { id: 'hsh24', name: 'Trash Bags',                 categoryId: 'household', unit: '' },
  { id: 'hsh25', name: 'Wet Wipes',                  categoryId: 'household', unit: '' },
  // ── Supplements ──────────────────────────────
  { id: 'sup01', name: 'Protein Whey Choco', categoryId: 'supplements', unit: '' },
  { id: 'sup02', name: 'Vitamin D',          categoryId: 'supplements', unit: '' },
  // ── Other ────────────────────────────────────
  { id: 'oth01', name: 'Beef Stock',            categoryId: 'other', unit: '' },
  { id: 'oth02', name: 'Tex Mex AH',            categoryId: 'other', unit: '' },
  { id: 'oth03', name: 'Digestive Cookies',     categoryId: 'other', unit: '' },
  { id: 'oth04', name: 'Chicken Stock',         categoryId: 'other', unit: '' },
  { id: 'oth05', name: 'Dumplings AH Chicken',  categoryId: 'other', unit: '' },
  { id: 'oth06', name: 'Crispy Onions',         categoryId: 'other', unit: '' },
];

// ══════════════════════════════════════════════
//  SEED RECIPES
//  These load once on first boot, then live in
//  localStorage like any other recipe.
// ══════════════════════════════════════════════

const SEED_RECIPES = [
  {
    id:           'recipe_adobo_chicken',
    name:         'Adobo Chicken',
    tag:          'dinner',
    photo:        'https://www.recipetineats.com/tachyon/2015/02/Filipino-Chicken-Adobo_7.jpg?resize=900%2C1260&zoom=1',
    favourite:    false,
    prepTime:     15,
    cookTime:     35,
    servings:     2,
    createdAt:    1700000000000,
    ingredients:  [
      { itemName: 'Chicken',       amount: 400,  unit: 'g'    },
      { itemName: 'Garlic',        amount: 4,    unit: 'clove'},
      { itemName: 'Soy Sauce',     amount: 42,   unit: 'ml'   },
      { itemName: 'White Vinegar', amount: 40,   unit: 'ml'   },
      { itemName: 'Bay Leaves',    amount: 4,    unit: 'piece'},
      { itemName: 'Olive Oil',     amount: 1,    unit: 'tbsp' },
      { itemName: 'Onion',         amount: 0.5,  unit: 'piece'},
      { itemName: 'Water',         amount: 180,  unit: 'ml'   },
      { itemName: 'Brown Sugar',   amount: 1,    unit: 'tbsp' },
      { itemName: 'Black Pepper',  amount: 2,    unit: 'tsp'  },
    ],
    instructions: [
      'Marinate the chicken (whenever, or the day before): mix 40ml white vinegar, 42ml soy sauce and 2 minced garlic cloves. Add the chicken and let it marinate.',
      'Heat a pan over medium-high heat. Cook the chicken on both sides for 2 minutes each until browned. Remove and set aside.',
      'Add 1 tbsp oil to the same pan. Add 0.5 diced onion and 2 minced garlic cloves. Cook for 1.5 minutes.',
      'Add 180ml water, 1 tbsp brown sugar, 2 tsp black pepper and the bay leaves. Simmer for 5 minutes.',
      'Add the chicken back in, smooth side up. Cook for 15 minutes.',
      'Flip the chicken. Cook for another 10 minutes until the sauce reduces to a thick, glossy glaze.',
    ],
  },
  {
    id:           'recipe_sloppy_joes',
    name:         'Sloppy Joes',
    tag:          'dinner',
    photo:        'https://www.sipandfeast.com/wp-content/uploads/2024/07/sloppy-joes-recipe-snippet-4.jpg',
    favourite:    false,
    prepTime:     10,
    cookTime:     20,
    servings:     4,
    createdAt:    1700000001000,
    ingredients:  [
      { itemName: 'Onion',              amount: 1,    unit: 'piece' },
      { itemName: 'Bell Peppers',       amount: 1,    unit: 'piece' },
      { itemName: 'Minced Beef',        amount: 300,  unit: 'g'     },
      { itemName: 'Salt',               amount: 0.5,  unit: 'tsp'   },
      { itemName: 'Chili Powder',       amount: 1,    unit: 'tsp'   },
      { itemName: 'Garlic',             amount: 2,    unit: 'clove' },
      { itemName: 'Worcestershire Sauce', amount: 1.5, unit: 'tsp'  },
      { itemName: 'Rice Vinegar',       amount: 1.5,  unit: 'tsp'   },
      { itemName: 'Ketchup',            amount: 75,   unit: 'ml'    },
      { itemName: 'Brown Sugar',        amount: 2,    unit: 'tsp'   },
      { itemName: 'Water',              amount: 40,   unit: 'ml'    },
    ],
    instructions: [
      'Heat a large pan to medium heat with olive oil. Add the diced onion and bell pepper. Sauté until soft, about 5 minutes.',
      'Add the minced beef and turn the heat to medium-high. Cook until browned (5–7 minutes), then mix in the salt and chili powder.',
      'Turn down to medium and add the minced garlic. Cook for 2 minutes until fragrant.',
      'Add the ketchup, brown sugar, rice vinegar, Worcestershire sauce, and water. Mix well and keep at a low simmer.',
      'Taste and adjust salt and pepper. Turn to low heat.',
      'Toast the buns cut-side down in a pan with a touch of olive oil until golden (1–2 minutes). Divide the beef mixture over 4 buns and serve.',
    ],
  },
  {
    id:           'recipe_shepherds_pie',
    name:         "Shepherd's Pie",
    tag:          'dinner',
    photo:        'https://www.sipandfeast.com/wp-content/uploads/2023/02/shepherds-pie-recipe-7.jpg',
    favourite:    false,
    prepTime:     20,
    cookTime:     60,
    servings:     4,
    createdAt:    1700000002000,
    ingredients:  [
      { itemName: 'Russet Potatoes',      amount: 700,  unit: 'g'      },
      { itemName: 'Parmigiano',           amount: 100,  unit: 'g'      },
      { itemName: 'Heavy Cream',          amount: 75,   unit: 'ml'     },
      { itemName: 'Butter',               amount: 40,   unit: 'g'      },
      { itemName: 'Eggs',                 amount: 1,    unit: 'yolk'   },
      { itemName: 'Ground Lamb',          amount: 300,  unit: 'g'      },
      { itemName: 'Peas',                 amount: 120,  unit: 'g'      },
      { itemName: 'Onion',                amount: 1,    unit: 'piece'  },
      { itemName: 'Celery',               amount: 1,    unit: 'rib'    },
      { itemName: 'Carrot',               amount: 1,    unit: 'piece'  },
      { itemName: 'Garlic',               amount: 2,    unit: 'clove'  },
      { itemName: 'Tomato Paste',         amount: 25,   unit: 'g'      },
      { itemName: 'Flour',                amount: 20,   unit: 'g'      },
      { itemName: 'Guinness',             amount: 1,    unit: 'bottle' },
      { itemName: 'Worcestershire Sauce', amount: 25,   unit: 'ml'     },
      { itemName: 'Thyme',                amount: 1,    unit: 'tsp'    },
      { itemName: 'Rosemary',             amount: 1,    unit: 'tsp'    },
      { itemName: 'Beef Stock',           amount: 160,  unit: 'ml'     },
    ],
    instructions: [
      'Add the potatoes to a pot of cold water, bring to a boil, and cook for 25-30 minutes until fork tender.',
      'Brown the ground lamb in a hot pan until fully cooked. Drain excess fat if needed.',
      'Add the diced celery and carrot. Cook until soft.',
      'Push the veg to the side, add the minced garlic. Cook 1-2 minutes until fragrant.',
      'Add the tomato paste, cook for a couple of minutes. If it starts to burn, add a small splash of water.',
      'Pour in the Guinness and increase to high heat. Reduce completely, about 5 minutes.',
      'Add the flour, stir for 1-2 minutes.',
      'Add the beef stock, frozen peas, thyme, rosemary and Worcestershire sauce. Bring to a boil then reduce to a low simmer. Let it reduce by half — trust your eyes. Taste and adjust seasoning.',
      'Drain the potatoes and mash or rice them. Mix in the melted butter, heavy cream, Parmigiano and salt (pepper if you like). Fold in the egg yolk and mix until smooth.',
      'Layer the lamb filling in a baking dish. Spread the mashed potato on top, finish with extra Parmigiano.',
      'Bake in a hot oven for 20 minutes on the top rack. Keep an eye on it.',
    ],
  },
  {
    id:        'recipe_chicken_broccoli_pasta',
    name:      'Chicken Broccoli Pasta',
    tag:       'dinner',
    photo:     'https://thecozycook.com/wp-content/uploads/2022/03/Chicken-and-Broccoli-Pasta-1.0.jpg',
    favourite: false,
    prepTime:  0,
    cookTime:  0,
    servings:  2,
    createdAt: 1700000003000,
    ingredients: [
      { itemName: 'Chicken',       amount: 0, unit: '' },
      { itemName: 'Broccoli',      amount: 0, unit: '' },
      { itemName: 'Cooking Cream', amount: 0, unit: '' },
      { itemName: 'Mustard',       amount: 0, unit: '' },
      { itemName: 'Salt',          amount: 0, unit: '' },
      { itemName: 'Black Pepper',  amount: 0, unit: '' },
    ],
    instructions: [],
  },
  {
    id:        'recipe_flammekueche',
    name:      'Flammekueche',
    tag:       'dinner',
    photo:     'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_iw/v1/img/recipes/36/52/98/zlnHjcK2RZC1aFGncNMC_TARTE_FLAMBEE_H_f.jpg',
    favourite: false,
    prepTime:  5,
    cookTime:  15,
    servings:  2,
    createdAt: 1700000004000,
    ingredients: [
      { itemName: 'Flammekeuche Dough', amount: 0,   unit: ''    },
      { itemName: 'Crème Fraîche',      amount: 125,  unit: 'g'   },
      { itemName: 'Onion',              amount: 1,    unit: 'piece'},
      { itemName: 'Smoked Bacon Cubes', amount: 0,    unit: ''    },
      { itemName: 'Munster or Morbier', amount: 0,    unit: ''    },
    ],
    instructions: [
      'Preheat the oven to 200°C.',
      'Place only the dough in the oven for 2-3 minutes. Stay close — it can burn fast.',
      'Take it out and spread the crème fraîche evenly over the dough.',
      'Add the sliced onions, cheese and bacon cubes on top.',
      'Put back in the oven. Check after 5 minutes — it\'s ready when the edges are golden and the cheese is melted.',
    ],
  },
  {
    id:        'recipe_cucumber_salad',
    name:      'Cucumber Salad',
    tag:       'lunch',
    photo:     'https://dishingouthealth.com/wp-content/uploads/2024/07/CucumberSesameSalad_Square.jpg',
    favourite: false,
    prepTime:  10,
    cookTime:  0,
    servings:  2,
    createdAt: 1700000005000,
    ingredients: [
      { itemName: 'Cucumber',     amount: 1,   unit: 'piece' },
      { itemName: 'Rice Vinegar', amount: 1,   unit: 'tbsp'  },
      { itemName: 'Sesame Oil',   amount: 2,   unit: 'tsp'   },
      { itemName: 'Ginger',       amount: 1.5, unit: 'tsp'   },
      { itemName: 'Soy Sauce',    amount: 2,   unit: 'tsp'   },
      { itemName: 'Sugar',        amount: 0.5, unit: 'tsp'   },
    ],
    instructions: [],
  },
  {
    id:        'recipe_poke_bowl',
    name:      'Poké Bowl',
    tag:       'lunch',
    photo:     'https://primary.jwwb.nl/public/p/k/q/temp-lpmgnefhkbgkjfjzhegm/m8d278/SurimiCrab.png',
    favourite: false,
    prepTime:  15,
    cookTime:  0,
    servings:  2,
    createdAt: 1700000006000,
    ingredients: [
      { itemName: 'Rice',        amount: 0, unit: '' },
      { itemName: 'Surimi',      amount: 0, unit: '' },
      { itemName: 'Sriracha Mayo', amount: 0, unit: '' },
      { itemName: 'Edamame',     amount: 0, unit: '' },
      { itemName: 'Mais',        amount: 0, unit: '' },
      { itemName: 'Avocado',     amount: 0, unit: '' },
      { itemName: 'Cucumber',    amount: 0, unit: '' },
      { itemName: 'Soy Sauce',   amount: 0, unit: '' },
    ],
    instructions: [],
  },
  {
    id:        'recipe_tex_mex_ah',
    name:      'Tex Mex AH Bowl',
    tag:       'dinner',
    photo:     'https://www.leukerecepten.nl/app/uploads/2022/03/chili-con-carne_.jpg',
    favourite: false,
    prepTime:  5,
    cookTime:  15,
    servings:  2,
    createdAt: 1700000007000,
    ingredients: [
      { itemName: 'Minced Beef',        amount: 300, unit: 'g'    },
      { itemName: 'Rice',               amount: 0,   unit: ''     },
      { itemName: 'Tex Mex AH',         amount: 1,   unit: 'pack' },
      { itemName: 'Chili Con Carne',    amount: 0,   unit: ''     },
      { itemName: 'Sour Cream',         amount: 0,   unit: ''     },
      { itemName: 'MSG',                amount: 0,   unit: ''     },
    ],
    instructions: [
      'Cook the precooked rice in a pan for 3 minutes.',
      'Season the minced beef with salt, pepper and chili con carne herbs. Cook for a couple of minutes until browned.',
      'Add the Tex Mex AH and the rice to the pan. Cook together for another 3 minutes.',
      'Serve with a side of sour cream.',
    ],
  },
  {
    id:        'recipe_garam_masala_curry',
    name:      'Curry - Garam Masala',
    tag:       'dinner',
    photo:     'https://nourishedkitchen.com/wp-content/uploads/2014/06/garam-masala-chicken-curry-primar-1-of-1.jpg',
    favourite: false,
    prepTime:  10,
    cookTime:  40,
    servings:  2,
    createdAt: 1700000008000,
    ingredients: [
      { itemName: 'Chicken Filet',  amount: 400, unit: 'g'    },
      { itemName: 'Coconut Milk',   amount: 400, unit: 'ml'   },
      { itemName: 'Garam Masala',   amount: 3,   unit: 'tbsp' },
      { itemName: 'Onion',          amount: 2,   unit: 'piece'},
      { itemName: 'Mushroom',       amount: 250, unit: 'g'    },
      { itemName: 'Ginger',         amount: 25,  unit: 'g'    },
      { itemName: 'Rice',           amount: 200, unit: 'g'    },
    ],
    instructions: [
      'Brown the onions in olive oil over medium heat until translucent.',
      'Add half of the garam masala, then add the chicken. Brown while stirring occasionally. Season with salt and pepper.',
      'Lower the heat. Add the ginger, pour in the coconut milk, add the remaining garam masala and the mushrooms.',
      'Simmer for about 30 minutes. Serve hot with rice.',
    ],
  },
  {
    id:        'recipe_knorr_burrito',
    name:      'Knorr Burrito',
    tag:       'dinner',
    photo:     'https://eviekookt.nl/wp-content/uploads/2020/02/PSX_20200207_201559-1200x675.jpg',
    favourite: false,
    prepTime:  15,
    cookTime:  30,
    servings:  2,
    createdAt: 1700000009000,
    ingredients: [
      { itemName: 'Chicken',                       amount: 400, unit: 'g'    },
      { itemName: 'Knorr Wereldgerechten Burrito',  amount: 1,   unit: 'pack' },
      { itemName: 'Wraps',                         amount: 0,   unit: ''     },
      { itemName: 'Yoghurt',                       amount: 0,   unit: ''     },
      { itemName: 'Grated Cheese',                 amount: 0,   unit: ''     },
      { itemName: 'Onion',                         amount: 1,   unit: 'piece'},
      { itemName: 'Paprika',                       amount: 1,   unit: 'piece'},
    ],
    instructions: [
      'Mix the Knorr sauce packet with Greek yoghurt and set aside — this is your sauce.',
      'Cook the chicken in a pan over medium-high heat until browned.',
      'Add the diced onion and paprika. Cook until soft.',
      'Add the Knorr herb mix with water and cook for 3 minutes, then cut the heat.',
      'Preheat the oven to 180°C.',
      'Smear the yoghurt sauce mix onto each wrap. Add the chicken filling and roll into rolls.',
      'Place the rolls on a baking tray and cover with grated cheese.',
      'Bake for 8-10 minutes until the cheese is golden.',
    ],
  },
  {
    id:        'recipe_gnocchi_salmon_leek',
    name:      'Gnocchi Salmon & Leek',
    tag:       'dinner',
    photo:     'https://skinnyspatula.com/wp-content/uploads/2022/03/Creamy_Salmon_Gnocchi_2.jpg',
    favourite: false,
    prepTime:  10,
    cookTime:  20,
    servings:  2,
    createdAt: 1700000010000,
    ingredients: [
      { itemName: 'Smoked Salmon',  amount: 100, unit: 'g'    },
      { itemName: 'Leek',           amount: 3,   unit: 'piece'},
      { itemName: 'Gnocchi',        amount: 500, unit: 'g'    },
      { itemName: 'Mustard',        amount: 1,   unit: 'tbsp' },
      { itemName: 'Cooking Cream',  amount: 100, unit: 'ml'   },
      { itemName: 'Parmigiano',     amount: 30,  unit: 'g'    },
      { itemName: 'Rucola',         amount: 0,   unit: ''     },
      { itemName: 'Lemon',          amount: 0,   unit: ''     },
    ],
    instructions: [
      'Cut the smoked salmon into pieces.',
      'Cook the sliced leek in a pan over medium heat until soft.',
      'Cook the gnocchi according to the packet.',
      'Last 3 minutes, add the smoked salmon to the leek.',
      'Add the dijon mustard and cooking cream to the leek. Stir and let it warm through.',
      'Add the drained gnocchi to the pan and mix everything together.',
      'Serve with fresh cracked pepper and Parmigiano. Top with a handful of rucola and a squeeze of lemon.',
    ],
  },
  {
    id:        'recipe_crepes',
    name:      'Crêpes',
    tag:       'dessert',
    photo:     'https://lacuisinedegeraldine.fr/wp-content/uploads/2025/01/Pate-a-crepes-recette-de-base-143-scaled.jpg',
    favourite: false,
    prepTime:  10,
    cookTime:  20,
    servings:  4,
    createdAt: 1700000011000,
    ingredients: [
      { itemName: 'Flour',         amount: 250, unit: 'g'    },
      { itemName: 'Eggs',          amount: 2,   unit: 'piece'},
      { itemName: 'Milk',          amount: 500, unit: 'ml'   },
      { itemName: 'Vanilla Sugar', amount: 1,   unit: 'bag'  },
      { itemName: 'Salt',          amount: 0,   unit: ''     },
      { itemName: 'Diplomatico',   amount: 1,   unit: 'shot' },
      { itemName: 'Butter',        amount: 0,   unit: ''     },
    ],
    instructions: [
      'Mix the flour and a pinch of salt in a bowl. Make a well in the centre and add the eggs.',
      'Gradually pour in the milk while whisking until you have a smooth, lump-free batter.',
      'Add the vanilla sugar and a shot of Diplomatico. Mix well. Let the batter rest for 10 minutes if you have time.',
      'Heat a pan over medium heat and melt a small knob of butter.',
      'Pour a ladle of batter into the pan and swirl to coat the bottom thinly. Cook until the edges lift, then flip.',
    ],
  },
  {
    id:        'recipe_pesto_pancetta_cake',
    name:      'Pesto & Pancetta Cake',
    tag:       'lunch',
    photo:     'https://assets.afcdn.com/recipe/20230424/142370_w1024h768c1cx1872cy2808cxt0cyt0cxb3744cyb5616.jpg',
    favourite: false,
    prepTime:  15,
    cookTime:  45,
    servings:  6,
    createdAt: 1700000012000,
    ingredients: [
      { itemName: 'Eggs',         amount: 4,   unit: 'piece' },
      { itemName: 'Pesto',        amount: 6,   unit: 'tbsp'  },
      { itemName: 'Flour',        amount: 150, unit: 'g'     },
      { itemName: 'Baking Powder',amount: 1,   unit: 'packet'},
      { itemName: 'Butter',       amount: 25,  unit: 'g'     },
      { itemName: 'Grated Cheese',amount: 70,  unit: 'g'     },
      { itemName: 'Goat Cheese',  amount: 0,   unit: '½ log' },
      { itemName: 'Pancetta',     amount: 0,   unit: ''      },
      { itemName: 'Salt',         amount: 0,   unit: ''      },
    ],
    instructions: [
      'Crack the eggs into a mixing bowl and beat them. Gradually add the pesto, flour, and baking powder. Finish with the melted butter.',
      'Mix well, then fold in the grated cheese, goat\'s cheese, and pancetta. Taste and add salt if needed.',
      'Pour the mixture into a loaf tin or small silicone moulds.',
      'Bake for 45 minutes at 200°C.',
    ],
  },
];
