/* ─────────────────────────────────────────────
   Grocery Confidential — listdatabase.js
   Edit this file to manage your categories and items.
   Do not touch app.js.
   ───────────────────────────────────────────── */

// ══════════════════════════════════════════════
//  CATEGORIES
//  Fields: id (unique, no spaces), name, emoji
// ══════════════════════════════════════════════

const DEFAULT_CATEGORIES = [
  { id: 'vegetables',   name: 'Vegetables',          emoji: '🥦' },
  { id: 'protein',      name: 'Protein',              emoji: '🥩' },
  { id: 'carbs',        name: 'Carbs',                emoji: '🍞' },
  { id: 'dairy',        name: 'Dairy',                emoji: '🥛' },
  { id: 'fruits',       name: 'Fruits',               emoji: '🍎' },
  { id: 'nuts_seeds',   name: 'Nuts & Seeds',          emoji: '🥜' },
  { id: 'oils',         name: 'Oils',                 emoji: '🫒' },
  { id: 'condiments',   name: 'Condiments & Sauces',  emoji: '🫙' },
  { id: 'herbs',        name: 'Herbs & Powders',       emoji: '🌿' },
  { id: 'baking',       name: 'Baking',               emoji: '🧁' },
  { id: 'cold_cuts',    name: 'Cold Cuts',             emoji: '🥓' },
  { id: 'drinks',       name: 'Drinks',               emoji: '🥤' },
  { id: 'cat_goods',    name: 'Cat Goods',             emoji: '🐱' },
  { id: 'canned_goods', name: 'Canned Goods',          emoji: '🥫' },
  { id: 'household',    name: 'Household',             emoji: '🧹' },
  { id: 'supplements',  name: 'Supplements',           emoji: '💊' },
  { id: 'other',        name: 'Other',                emoji: '📦' },
];

// ══════════════════════════════════════════════
//  ITEMS
//  Fields:
//    id         — unique string, no spaces
//    name       — display name
//    categoryId — must match an id above
//    unit       — optional (e.g. 'kg', 'pack') or ''
// ══════════════════════════════════════════════

const DEFAULT_ITEMS = [
  // ── Vegetables ───────────────────────────────
  { id: 'veg01', name: 'Asparagus',       categoryId: 'vegetables', unit: '' },
  { id: 'veg02', name: 'Avocado',         categoryId: 'vegetables', unit: '' },
  { id: 'veg03', name: 'Bell Peppers',    categoryId: 'vegetables', unit: '' },
  { id: 'veg04', name: 'Bimi',            categoryId: 'vegetables', unit: '' },
  { id: 'veg05', name: 'Broccoli',        categoryId: 'vegetables', unit: '' },
  { id: 'veg06', name: 'Carrot',          categoryId: 'vegetables', unit: '' },
  { id: 'veg07', name: 'Cucumber',        categoryId: 'vegetables', unit: '' },
  { id: 'veg08', name: 'Garlic',          categoryId: 'vegetables', unit: '' },
  { id: 'veg09', name: 'Ginger',          categoryId: 'vegetables', unit: '' },
  { id: 'veg10', name: 'Leek',            categoryId: 'vegetables', unit: '' },
  { id: 'veg11', name: 'Lemon',           categoryId: 'vegetables', unit: '' },
  { id: 'veg12', name: 'Lime',            categoryId: 'vegetables', unit: '' },
  { id: 'veg13', name: 'Mais',            categoryId: 'vegetables', unit: '' },
  { id: 'veg14', name: 'Mushroom',        categoryId: 'vegetables', unit: '' },
  { id: 'veg15', name: 'Onion',           categoryId: 'vegetables', unit: '' },
  { id: 'veg16', name: 'Paprika',         categoryId: 'vegetables', unit: '' },
  { id: 'veg17', name: 'Potato',          categoryId: 'vegetables', unit: '' },
  { id: 'veg18', name: 'Rucola',          categoryId: 'vegetables', unit: '' },
  { id: 'veg19', name: 'Spring Onion',    categoryId: 'vegetables', unit: '' },
  { id: 'veg20', name: 'Sweet Potato',    categoryId: 'vegetables', unit: '' },
  { id: 'veg21', name: 'Tomato',          categoryId: 'vegetables', unit: '' },
  { id: 'veg22', name: 'Edamame',         categoryId: 'vegetables', unit: '' },
  { id: 'veg23', name: 'Shallot',         categoryId: 'vegetables', unit: '' },
  { id: 'veg24', name: 'Peas',            categoryId: 'vegetables', unit: '' },
  { id: 'veg25', name: 'Celery',          categoryId: 'vegetables', unit: '' },
  // ── Protein ──────────────────────────────────
  { id: 'pro01', name: 'Chicken Thigh',       categoryId: 'protein', unit: '' },
  { id: 'pro02', name: 'Chicken Filet',       categoryId: 'protein', unit: '' },
  { id: 'pro03', name: 'Eggs',               categoryId: 'protein', unit: '' },
  { id: 'pro04', name: 'Minced Beef',         categoryId: 'protein', unit: '' },
  { id: 'pro05', name: 'Minced Half/Half',    categoryId: 'protein', unit: '' },
  { id: 'pro06', name: 'Salmon',             categoryId: 'protein', unit: '' },
  { id: 'pro07', name: 'Smoked Salmon',       categoryId: 'protein', unit: '' },
  { id: 'pro08', name: 'Steak',              categoryId: 'protein', unit: '' },
  { id: 'pro09', name: 'Duck',               categoryId: 'protein', unit: '' },
  { id: 'pro10', name: 'Shrimp',             categoryId: 'protein', unit: '' },
  { id: 'pro11', name: 'Surimi',             categoryId: 'protein', unit: '' },
  { id: 'pro12', name: 'Guanciale',          categoryId: 'protein', unit: '' },
  { id: 'pro13', name: 'Pancetta',           categoryId: 'protein', unit: '' },
  { id: 'pro14', name: 'Smoked Bacon Cubes', categoryId: 'protein', unit: '' },
  { id: 'pro15', name: 'Italian Sausage',    categoryId: 'protein', unit: '' },
  // ── Carbs ────────────────────────────────────
  { id: 'car01', name: 'Bread',               categoryId: 'carbs', unit: '' },
  { id: 'car02', name: 'Flammekeuche Dough',  categoryId: 'carbs', unit: '' },
  { id: 'car03', name: 'Fusilli',             categoryId: 'carbs', unit: '' },
  { id: 'car04', name: 'Gnocchi',             categoryId: 'carbs', unit: '' },
  { id: 'car05', name: 'Lasagna',             categoryId: 'carbs', unit: '' },
  { id: 'car06', name: 'Noodles',             categoryId: 'carbs', unit: '' },
  { id: 'car07', name: 'Oatmeal',             categoryId: 'carbs', unit: '' },
  { id: 'car08', name: 'Penne',               categoryId: 'carbs', unit: '' },
  { id: 'car09', name: 'Quinoa',              categoryId: 'carbs', unit: '' },
  { id: 'car10', name: 'Rice',                categoryId: 'carbs', unit: '' },
  { id: 'car11', name: 'Spaghetti',           categoryId: 'carbs', unit: '' },
  { id: 'car12', name: 'Tagliatelle',         categoryId: 'carbs', unit: '' },
  { id: 'car13', name: 'Tortellini',          categoryId: 'carbs', unit: '' },
  { id: 'car14', name: 'Wraps',               categoryId: 'carbs', unit: '' },
  // ── Dairy ────────────────────────────────────
  { id: 'dai01', name: 'Butter',          categoryId: 'dairy', unit: '' },
  { id: 'dai02', name: 'Cheese',          categoryId: 'dairy', unit: '' },
  { id: 'dai03', name: 'Coconut Milk',    categoryId: 'dairy', unit: '' },
  { id: 'dai04', name: 'Cooking Cream',   categoryId: 'dairy', unit: '' },
  { id: 'dai05', name: 'Crème Fraîche',   categoryId: 'dairy', unit: '' },
  { id: 'dai06', name: 'Goat Cheese',     categoryId: 'dairy', unit: '' },
  { id: 'dai07', name: 'Grated Cheese',   categoryId: 'dairy', unit: '' },
  { id: 'dai08', name: 'Heavy Cream',     categoryId: 'dairy', unit: '' },
  { id: 'dai09', name: 'Milk',            categoryId: 'dairy', unit: '' },
  { id: 'dai10', name: 'Morbier',         categoryId: 'dairy', unit: '' },
  { id: 'dai11', name: 'Mozzarella',      categoryId: 'dairy', unit: '' },
  { id: 'dai12', name: 'Munster',         categoryId: 'dairy', unit: '' },
  { id: 'dai13', name: 'Parmigiano',      categoryId: 'dairy', unit: '' },
  { id: 'dai14', name: 'Quark (Kwark)',   categoryId: 'dairy', unit: '' },
  { id: 'dai15', name: 'Sour Cream',      categoryId: 'dairy', unit: '' },
  { id: 'dai16', name: 'Yoghurt',         categoryId: 'dairy', unit: '' },
  { id: 'dai17', name: 'Cheddar',         categoryId: 'dairy', unit: '' },
  // ── Fruits ───────────────────────────────────
  { id: 'fru01', name: 'Apple',       categoryId: 'fruits', unit: '' },
  { id: 'fru02', name: 'Banana',      categoryId: 'fruits', unit: '' },
  { id: 'fru03', name: 'Blackberry',  categoryId: 'fruits', unit: '' },
  { id: 'fru04', name: 'Kiwi',        categoryId: 'fruits', unit: '' },
  { id: 'fru05', name: 'Mandarin',    categoryId: 'fruits', unit: '' },
  { id: 'fru06', name: 'Red Grapes',  categoryId: 'fruits', unit: '' },
  // ── Nuts & Seeds ─────────────────────────────
  { id: 'nut01', name: 'Pine',          categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut02', name: 'Almonds',       categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut03', name: 'Pecan',         categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut04', name: 'Cashew',        categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut05', name: 'Pistachio',     categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut06', name: 'Sesame Seeds',  categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut07', name: 'Fennel Seeds',  categoryId: 'nuts_seeds', unit: '' },
  { id: 'nut08', name: 'Chia Seeds',    categoryId: 'nuts_seeds', unit: '' },
  // ── Oils ─────────────────────────────────────
  { id: 'oil01', name: 'White Vinegar',   categoryId: 'oils', unit: '' },
  { id: 'oil02', name: 'Rice Vinegar',    categoryId: 'oils', unit: '' },
  { id: 'oil03', name: 'Sesame Oil',      categoryId: 'oils', unit: '' },
  { id: 'oil04', name: 'Chili Oil',       categoryId: 'oils', unit: '' },
  { id: 'oil05', name: 'Sun Flower Oil',  categoryId: 'oils', unit: '' },
  { id: 'oil06', name: 'Balsamico Cream', categoryId: 'oils', unit: '' },
  { id: 'oil07', name: 'Olive Oil',       categoryId: 'oils', unit: '' },
  { id: 'oil08', name: 'Mirin',           categoryId: 'oils', unit: '' },
  // ── Condiments & Sauces ──────────────────────
  { id: 'con01', name: 'BBQ Sauce',              categoryId: 'condiments', unit: '' },
  { id: 'con02', name: 'Cider Vinegar',           categoryId: 'condiments', unit: '' },
  { id: 'con03', name: 'Gochujang',              categoryId: 'condiments', unit: '' },
  { id: 'con04', name: 'Hoisin Sauce',            categoryId: 'condiments', unit: '' },
  { id: 'con05', name: 'Honey',                  categoryId: 'condiments', unit: '' },
  { id: 'con06', name: 'Ketchup',                categoryId: 'condiments', unit: '' },
  { id: 'con07', name: 'LKK Black Bean Garlic',  categoryId: 'condiments', unit: '' },
  { id: 'con08', name: 'Mayonaise',              categoryId: 'condiments', unit: '' },
  { id: 'con09', name: 'Mustard',                categoryId: 'condiments', unit: '' },
  { id: 'con10', name: 'Nocciolata',             categoryId: 'condiments', unit: '' },
  { id: 'con11', name: 'Pesto',                  categoryId: 'condiments', unit: '' },
  { id: 'con12', name: 'Soy Sauce',              categoryId: 'condiments', unit: '' },
  { id: 'con13', name: 'Sriracha',               categoryId: 'condiments', unit: '' },
  { id: 'con14', name: 'Sriracha Mayo',           categoryId: 'condiments', unit: '' },
  { id: 'con15', name: 'Tomato Paste',            categoryId: 'condiments', unit: '' },
  { id: 'con16', name: 'Truffle Mayo',            categoryId: 'condiments', unit: '' },
  { id: 'con17', name: 'Water',                  categoryId: 'condiments', unit: '' },
  { id: 'con18', name: 'Worcestershire Sauce',   categoryId: 'condiments', unit: '' },
  // ── Herbs & Powders ──────────────────────────
  { id: 'her01', name: 'Basil',                          categoryId: 'herbs', unit: '' },
  { id: 'her02', name: 'Bay Leaves',                     categoryId: 'herbs', unit: '' },
  { id: 'her03', name: 'Black Pepper',                   categoryId: 'herbs', unit: '' },
  { id: 'her04', name: 'Burrito Kruidenmix Santa Maria', categoryId: 'herbs', unit: '' },
  { id: 'her05', name: 'Chili Con Carne',                categoryId: 'herbs', unit: '' },
  { id: 'her06', name: 'Garam Masala',                   categoryId: 'herbs', unit: '' },
  { id: 'her07', name: 'Garlic Powder',                  categoryId: 'herbs', unit: '' },
  { id: 'her08', name: 'MSG',                            categoryId: 'herbs', unit: '' },
  { id: 'her09', name: 'Onion Powder',                   categoryId: 'herbs', unit: '' },
  { id: 'her10', name: 'Parsley',                        categoryId: 'herbs', unit: '' },
  { id: 'her11', name: 'PB2',                            categoryId: 'herbs', unit: '' },
  { id: 'her12', name: 'Red Pepper Flakes',              categoryId: 'herbs', unit: '' },
  { id: 'her13', name: 'Rosemary',                       categoryId: 'herbs', unit: '' },
  { id: 'her14', name: 'Salt',                           categoryId: 'herbs', unit: '' },
  { id: 'her15', name: 'Thyme',                          categoryId: 'herbs', unit: '' },
  // ── Baking ───────────────────────────────────
  { id: 'bak01', name: 'Chocolate Chips',  categoryId: 'baking', unit: '' },
  { id: 'bak02', name: 'Cooking Chocolate',categoryId: 'baking', unit: '' },
  { id: 'bak03', name: 'Crystal Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak04', name: 'Bastard Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak05', name: 'Flour',            categoryId: 'baking', unit: '' },
  { id: 'bak06', name: 'Cinnamon',         categoryId: 'baking', unit: '' },
  { id: 'bak07', name: 'Baking Soda',      categoryId: 'baking', unit: '' },
  { id: 'bak08', name: 'Vanilla Extract',  categoryId: 'baking', unit: '' },
  { id: 'bak09', name: 'Brown Sugar',      categoryId: 'baking', unit: '' },
  { id: 'bak10', name: 'Sugar',            categoryId: 'baking', unit: '' },
  { id: 'bak11', name: 'Baking Powder',    categoryId: 'baking', unit: '' },
  { id: 'bak12', name: 'Vanilla Sugar',    categoryId: 'baking', unit: '' },
  { id: 'bak13', name: 'Almond Flour',     categoryId: 'baking', unit: '' },
  // ── Cold Cuts ────────────────────────────────
  { id: 'cut01', name: 'Achterham',    categoryId: 'cold_cuts', unit: '' },
  { id: 'cut02', name: 'Beenham',      categoryId: 'cold_cuts', unit: '' },
  { id: 'cut03', name: 'Cheese Cuts',  categoryId: 'cold_cuts', unit: '' },
  { id: 'cut04', name: 'Chorizo',      categoryId: 'cold_cuts', unit: '' },
  { id: 'cut05', name: 'Salami',       categoryId: 'cold_cuts', unit: '' },
  // ── Drinks ───────────────────────────────────
  { id: 'drk01', name: 'Cola',          categoryId: 'drinks', unit: '' },
  { id: 'drk02', name: 'Diplomatico',   categoryId: 'drinks', unit: '' },
  { id: 'drk03', name: 'Guinness',      categoryId: 'drinks', unit: '' },
  { id: 'drk04', name: "Jus d'orange",  categoryId: 'drinks', unit: '' },
  { id: 'drk05', name: 'Nescafé Gold',  categoryId: 'drinks', unit: '' },
  { id: 'drk06', name: 'White Wine',    categoryId: 'drinks', unit: '' },
  { id: 'drk07', name: 'Beer',          categoryId: 'drinks', unit: '' },
  // ── Cat Goods ────────────────────────────────
  { id: 'cat01', name: 'Kibble',          categoryId: 'cat_goods', unit: '' },
  { id: 'cat02', name: 'Gourmet Mousse',  categoryId: 'cat_goods', unit: '' },
  { id: 'cat03', name: 'Litter',          categoryId: 'cat_goods', unit: '' },
  { id: 'cat04', name: 'L-Lysine',        categoryId: 'cat_goods', unit: '' },
  { id: 'cat05', name: 'Catisfaction',    categoryId: 'cat_goods', unit: '' },
  // ── Canned Goods ─────────────────────────────
  { id: 'can01', name: 'Canned Tomatoes',                  categoryId: 'canned_goods', unit: '' },
  { id: 'can02', name: 'Canned Tuna',                      categoryId: 'canned_goods', unit: '' },
  { id: 'can03', name: 'Bonduelle Bonenmix',               categoryId: 'canned_goods', unit: '' },
  { id: 'can04', name: 'Bonduelle Mexicana Mix',           categoryId: 'canned_goods', unit: '' },
  { id: 'can05', name: 'Kühne Rauwkost',                   categoryId: 'canned_goods', unit: '' },
  { id: 'can06', name: 'Pickled Green Pepper',             categoryId: 'canned_goods', unit: '' },
  { id: 'can07', name: 'Knorr Wereldgerechten Burrito',    categoryId: 'canned_goods', unit: '' },
  { id: 'can08', name: 'Pickled Red Onion',                categoryId: 'canned_goods', unit: '' },
  // ── Household ────────────────────────────────
  { id: 'hsh01', name: 'Aloe Vera Lotion',           categoryId: 'household', unit: '' },
  { id: 'hsh02', name: 'Blue Wonder Disinfect Wipes', categoryId: 'household', unit: '' },
  { id: 'hsh03', name: 'Boterhamzakje',              categoryId: 'household', unit: '' },
  { id: 'hsh04', name: 'Condoms',                    categoryId: 'household', unit: '' },
  { id: 'hsh05', name: 'Cotton Buds',                categoryId: 'household', unit: '' },
  { id: 'hsh06', name: 'Cotton Pads Round',          categoryId: 'household', unit: '' },
  { id: 'hsh07', name: 'Dish Soap',                  categoryId: 'household', unit: '' },
  { id: 'hsh08', name: 'Dishwasher Rinse',           categoryId: 'household', unit: '' },
  { id: 'hsh09', name: 'Dishwasher Salt',            categoryId: 'household', unit: '' },
  { id: 'hsh10', name: 'Dishwasher Tablets',         categoryId: 'household', unit: '' },
  { id: 'hsh11', name: 'Green Soap',                 categoryId: 'household', unit: '' },
  { id: 'hsh12', name: 'Hand Soap',                  categoryId: 'household', unit: '' },
  { id: 'hsh13', name: 'Kitchen Paper',              categoryId: 'household', unit: '' },
  { id: 'hsh14', name: 'Laundry Soap',               categoryId: 'household', unit: '' },
  { id: 'hsh15', name: 'Nose Spray',                 categoryId: 'household', unit: '' },
  { id: 'hsh16', name: 'Paracetamol',                categoryId: 'household', unit: '' },
  { id: 'hsh17', name: 'Skewers',                    categoryId: 'household', unit: '' },
  { id: 'hsh18', name: 'Throat Medicine',            categoryId: 'household', unit: '' },
  { id: 'hsh19', name: 'Tissues',                    categoryId: 'household', unit: '' },
  { id: 'hsh20', name: 'Toilet Paper',               categoryId: 'household', unit: '' },
  { id: 'hsh21', name: 'Toothbrush',                 categoryId: 'household', unit: '' },
  { id: 'hsh22', name: 'Toothpaste',                 categoryId: 'household', unit: '' },
  { id: 'hsh23', name: 'Toothpick Floss',            categoryId: 'household', unit: '' },
  { id: 'hsh24', name: 'Trash Bags',                 categoryId: 'household', unit: '' },
  { id: 'hsh25', name: 'Wet Wipes',                  categoryId: 'household', unit: '' },
  // ── Supplements ──────────────────────────────
  { id: 'sup01', name: 'Protein Whey Choco', categoryId: 'supplements', unit: '' },
  { id: 'sup02', name: 'Vitamin D',          categoryId: 'supplements', unit: '' },
  // ── Other ────────────────────────────────────
  { id: 'oth01', name: 'Beef Stock',            categoryId: 'other', unit: '' },
  { id: 'oth02', name: 'Tex Mex AH',            categoryId: 'other', unit: '' },
  { id: 'oth03', name: 'Digestive Cookies',     categoryId: 'other', unit: '' },
  { id: 'oth04', name: 'Chicken Stock',         categoryId: 'other', unit: '' },
  { id: 'oth05', name: 'Dumplings AH Chicken',  categoryId: 'other', unit: '' },
  { id: 'oth06', name: 'Crispy Onions',         categoryId: 'other', unit: '' },
];
